/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_graycomputendk_JNIHelper */

#ifndef _Included_com_example_graycomputendk_JNIHelper
#define _Included_com_example_graycomputendk_JNIHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_graycomputendk_JNIHelper
 * Method:    nativeMono
 * Signature: (IILjava/lang/Object;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_example_graycomputendk_JNIHelper_nativeMono
  (JNIEnv *, jclass, jint, jint, jobject, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
